name: heroes
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  angel_framework: ^2.1.0
  angel_proxy: ^2.2.0
  angel_static: ^2.1.3+2

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  http_server: ^0.9.8