<<<<<<< HEAD
name: my_hell
description: my_shell
environment:
  sdk: any
dev_dependencies:
  angel_framework: ^2.1.0
  angel_proxy: ^2.2.0
  angel_static: ^2.1.3+2
=======
name: my_hell
description: my_shell
environment:
  sdk: any
dev_dependencies:
  angel_framework: ^2.1.0
  angel_proxy: ^2.2.0
  angel_static: ^2.1.3+2
>>>>>>> 1f60fdc591439f5b86c2a9c41e5c0f8638162731
