name: angular_dart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Niskaaaa <49870606+Niskaaaa@users.noreply.github.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.1.2
  convert: any

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
